# Generated by Django 4.1.7 on 2023-11-30 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_activities_organization_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities_inputs',
            name='organization_id',
        ),
        migrations.RemoveField(
            model_name='activities_inputs',
            name='project_id',
        ),
    ]
