# Generated by Django 4.1.7 on 2024-03-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_activities_inputs_organization_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='activity_name',
            field=models.CharField(default=None, max_length=1000, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_name',
            field=models.CharField(default=None, max_length=500, verbose_name='Project Title'),
        ),
    ]
