# Generated by Django 4.1.7 on 2024-04-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_activities_activity_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities_inputs',
            name='activity_input_expenses',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20, verbose_name='Expenditure'),
        ),
    ]
