# Generated by Django 4.1.7 on 2024-08-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_activities_inputs_activity_input_double_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdp_populations',
            name='budget_health',
            field=models.BigIntegerField(default=0, verbose_name='Government budget on Health'),
        ),
        migrations.AddField(
            model_name='gdp_populations',
            name='expenditure_health',
            field=models.BigIntegerField(default=0, verbose_name='Government Expenditure on Health'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('', '--select--'), ('super-admin', 'Super Admin'), ('activity-manager', 'Activity Manager'), ('data-reporter', 'Data Reporter')], default='other', max_length=20, verbose_name='Type'),
        ),
    ]
